# Generated by Django 4.1.3 on 2022-12-16 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsBreadcumbArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name=datetime.date)),
            ],
        ),
        migrations.CreateModel(
            name='AddvertiseWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_title', models.CharField(max_length=50)),
                ('advert_thumb', models.ImageField(upload_to='pics')),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BreakingNewsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaultbreaking', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BreakingNewsWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_title', models.CharField(max_length=50)),
                ('widgetimg', models.ImageField(upload_to='pics')),
                ('widgetbreakingnewstitle', models.CharField(max_length=100)),
                ('widgetheadline', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BrowserIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/pics')),
            ],
        ),
        migrations.CreateModel(
            name='CatagoryGazetteWelcomePostAreaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gazetteposttag', models.CharField(max_length=30)),
                ('gazettepostheadline', models.CharField(max_length=30)),
                ('gazettepostdate', models.DateField(auto_now_add=True)),
                ('gazettepostimg', models.ImageField(upload_to='pics')),
                ('gazettepostparagraph', models.TextField(max_length=2000)),
                ('gazettepostbtn', models.CharField(max_length=20)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatagoryGazetteWelcomePostAreab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gazetteposttag', models.CharField(max_length=30)),
                ('gazettepostheadline', models.CharField(max_length=30)),
                ('gazettepostdate', models.DateField(auto_now_add=True)),
                ('gazettepostimg', models.ImageField(upload_to='pics')),
                ('gazettepostparagraph', models.TextField(max_length=2000)),
                ('gazettepostbtn', models.CharField(max_length=20)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatagoryGazetteWelcomePostAreac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gazetteposttag', models.CharField(max_length=30)),
                ('gazettepostheadline', models.CharField(max_length=30)),
                ('gazettepostdate', models.DateField(auto_now_add=True)),
                ('gazettepostimg', models.ImageField(upload_to='pics')),
                ('gazettepostparagraph', models.TextField(max_length=2000)),
                ('gazettepostbtn', models.CharField(max_length=20)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryBreadcumbArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('date', models.DateField(verbose_name=datetime.date)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('msg', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactAddressInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('infopara1', models.CharField(max_length=50)),
                ('infopara2', models.CharField(max_length=50)),
                ('infopara3', models.CharField(max_length=50)),
                ('phoneheading', models.CharField(max_length=50)),
                ('contactinfo1', models.CharField(max_length=50)),
                ('contactinfo2', models.CharField(max_length=50)),
                ('contactinfo3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsBreadcumbArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name=datetime.date)),
            ],
        ),
        migrations.CreateModel(
            name='DoNotMiss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_title', models.CharField(max_length=20)),
                ('post_thumbimg', models.ImageField(upload_to='pics')),
                ('post_content', models.CharField(max_length=50)),
                ('url', models.URLField(null=True)),
                ('date', models.DateField(verbose_name=datetime.date)),
            ],
        ),
        migrations.CreateModel(
            name='EditorialPostSingleSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('tag', models.CharField(max_length=20)),
                ('url', models.URLField(null=True)),
                ('headline', models.CharField(max_length=50)),
                ('headlineafterbr', models.CharField(max_length=150)),
                ('date', models.DateField(auto_now_add=True)),
                ('para', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='FooterBgImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='FooterHeadlinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FooterHeadlineb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FooterHeadlinec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FooterHeadlined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FooterHeadlinee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FooterHeadlinef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FooterWidgetLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=10)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterWidgetListb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=10)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterWidgetListc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=10)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterWidgetListd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=10)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterWidgetListe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=10)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterWidgetListf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=10)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GazetteAboutUsArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('paragraph1', models.TextField(max_length=3000)),
                ('paragraph2', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='GazetteContactArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=30)),
                ('formtext', models.TextField(max_length=500)),
                ('formemail', models.EmailField(max_length=30)),
                ('formmsg', models.TextField(max_length=500)),
                ('formbtn', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GazetteCtaArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('heading', models.CharField(max_length=100)),
                ('paragraph', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderAddvertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveCommentArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('formtext', models.CharField(max_length=100)),
                ('formemail', models.EmailField(max_length=30, null=True)),
                ('formmsg', models.TextField(max_length=250)),
                ('formbtn', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marquee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NavItemDropDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaginationListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaginationListNextButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
                ('num', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchposttag', models.CharField(max_length=30)),
                ('searchpostheadline', models.CharField(max_length=30)),
                ('searchpostdate', models.DateField(auto_now_add=True)),
                ('searchpostimg', models.ImageField(upload_to='pics')),
                ('searchpostparagraph', models.TextField(max_length=2000)),
                ('searchpostbtn', models.CharField(max_length=20)),
                ('searchurl', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SingleBlogPostContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgimg', models.ImageField(upload_to='pics')),
                ('tag', models.CharField(max_length=20)),
                ('short_news', models.TextField(max_length=5000)),
                ('date', models.DateField(auto_now_add=True)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SinglePostArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('tag', models.CharField(max_length=100)),
                ('url', models.URLField(null=True)),
                ('heading', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name=datetime.date)),
            ],
        ),
        migrations.CreateModel(
            name='SinglePostAreaContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(max_length=100)),
                ('p2', models.CharField(max_length=100)),
                ('p3', models.CharField(max_length=100)),
                ('imgthumb', models.ImageField(upload_to='pics')),
                ('ptext1', models.CharField(max_length=100)),
                ('ptext2', models.CharField(max_length=100)),
                ('blockqts', models.CharField(max_length=100)),
                ('singleptxt', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SinglePostDiscussionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('commentperson', models.CharField(max_length=20)),
                ('commentdate', models.DateField(verbose_name=datetime.date)),
                ('commenttext', models.TextField(max_length=100)),
                ('replybtn', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SinglePostTodayHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SingleTeamArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('sociallinks', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SingleVideoPostArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('video', models.FileField(null=True, upload_to='videos_uploaded')),
                ('headline', models.CharField(max_length=50)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.URLField(max_length=100)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StockReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencyname', models.CharField(max_length=10)),
                ('currencyvalue', models.FloatField(max_length=10)),
                ('currencyminusindex', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('btnsubscribe', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TeamArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaultname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tricker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(null=True)),
            ],
        ),
    ]
