# Generated by Django 4.1.3 on 2022-12-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GazetteCtaArea',
        ),
    ]
