# Generated by Django 4.1.3 on 2022-12-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0003_gazettectaarea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentBox',
        ),
    ]
