# Generated by Django 4.1.3 on 2023-02-05 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0006_culturalnewsarea_sportnewsarea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleVideoPostArea',
        ),
    ]
