# Generated by Django 4.1.3 on 2023-05-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0009_alter_breakingnewstitle_defaultbreaking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleteamarea',
            name='detail',
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
