# Generated by Django 4.1.3 on 2023-02-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postdetail', '0004_singleteamarea_sociallink_teamarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatagoryGazetteWelcomePostAreaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gazetteposttag', models.CharField(max_length=30)),
                ('gazettepostheadline', models.CharField(max_length=30)),
                ('gazettepostdate', models.DateField(auto_now_add=True)),
                ('gazettepostimg', models.ImageField(upload_to='pics')),
                ('gazettepostparagraph', models.TextField(max_length=2000)),
                ('gazettepostbtn', models.CharField(max_length=20)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatagoryGazetteWelcomePostAreab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gazetteposttag', models.CharField(max_length=30)),
                ('gazettepostheadline', models.CharField(max_length=30)),
                ('gazettepostdate', models.DateField(auto_now_add=True)),
                ('gazettepostimg', models.ImageField(upload_to='pics')),
                ('gazettepostparagraph', models.TextField(max_length=2000)),
                ('gazettepostbtn', models.CharField(max_length=20)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatagoryGazetteWelcomePostAreac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gazetteposttag', models.CharField(max_length=30)),
                ('gazettepostheadline', models.CharField(max_length=30)),
                ('gazettepostdate', models.DateField(auto_now_add=True)),
                ('gazettepostimg', models.ImageField(upload_to='pics')),
                ('gazettepostparagraph', models.TextField(max_length=2000)),
                ('gazettepostbtn', models.CharField(max_length=20)),
                ('url', models.URLField(null=True)),
            ],
        ),
    ]
