# Generated by Django 4.1.3 on 2023-05-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postdetail', '0006_editorialpostsingleslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleteamarea',
            name='detail',
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
