# Generated by Django 4.1.3 on 2022-12-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mssg', models.TextField(max_length=300)),
            ],
        ),
    ]
